### ISSUE TITLE
NoClassDefFoundError thrown at startup

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-radius#3]
Running `super-gluu-radius-server` build at 2020-07-10 23:12 throws the following errors:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/LoggerContextShutdownAware
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.createContextSelector(Log4jContextFactory.java:106)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:59)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:94)
        at org.apache.log4j.Logger.getLogger(Logger.java:41)
        at org.gluu.radius.ServerEntry.<clinit>(ServerEntry.java:47)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.spi.LoggerContextShutdownAware
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 19 more
```

This issue affects `gluufederation/radius:4.2.0_dev` image.

**Comment by iromli** [comment]
@uprightech is there any extra dependencies need to be installed?

**Comment by uprightech** [comment]
@iromli  in principle, no. But let me check.

**Comment by iromli** [comment]
Fixed in https://ox.gluu.org/maven/org/gluu/super-gluu-radius-server/4.2.0.Final/ build at 2020-07-15 18:57.

**Comment by MarcMueltin** [comment]
I encounter the same error in my application that uses log4j. In my Maven .pom file, I refer to the dependencies log4j-core and log4j-api in version 2.13.1. I wonder what was your solution.

**Comment by hazemkhaled094** [comment]
@MarcMueltin How did you solve the issue? I get the same error, although everythings passes locally.
